### ISSUE TITLE
Wrong character encoding in track titles

### ISSUE THREAD

**Issue by srousset** [karimknaebel/phonograph-issue-tracker#128]
Hello,

Congratulations on an excellent and nice-looking app. I really like it...

... but it has a problem to correctly display diacritical characters (such as é or ä or è or ö, etc.). In some cases but not in all cases... And apparently only on track titles, not on album titles.

The problem is that  1) the accentuated characters show as messy combinations of characters,  but 2) when I want to edit them, they show all clean in the edit window!

See this PDF for screen shots: [Phonograph wrong character encoding.pdf](https://github.com/kabouzeid/phonograph-issue-tracker/files/404631/Phonograph.wrong.character.encoding.pdf). Hopefully it's self-explanatory.

I hope you can easily fix it. And if you can, it would be nice to say what were the two incompatible character encodings that were involved. (That could help for other apps where I've seen similar problems. Not on Android though.)

Thanks and best regards, Stéphane

**Comment by paulheising** [comment]
Also observed this issue. I think the Android Mediascanner is the problem here. For me, this workaround helped:

Got the app "ID3Fixer" from Google Play. Selected all files in my music directory, charset to windows-1252 (Western European). Than let the app fix it inside the android media database. I think, as long as the source file is not changed, this will be permanent, but I'm not sure.

For me, fixing it in the source file did not work. Probably because the files are not corrupted at all, but android mediascanner is. Fixing it in the media database makes everything work fine in phonograph and other players. Hopefully google will fix this soon.

**Comment by srousset** [comment]
Thank you pmattke, your solution worked for me exactly as you described (including the non-working at the level of the source file, and the good solution when applying the fix to the Android database). Thanks much.

Best regards, Stéphane

**Comment by Shudouken** [comment]
I just encountered this problem as well with some Russian characters.
Great and easy fix, thanks @pmattke

**Comment by arkon** [comment]
You can also use [mp3val](http://mp3val.sourceforge.net/) to try fixing mp3 files too.
