### ISSUE TITLE
Album view playback does not follow track order, next track is seemingly random

### ISSUE THREAD

**Issue by eggsgent** [karimknaebel/phonograph-issue-tracker#15]
App Version 0.11.0 RC, Samsung G930F (Galaxy S7) - Android 6.0.1
1. Go to the Albums tab
2. Select an album, notice the name of track 2
3. Select track 1 and let it play through so that next song starts automatically

Expected: track 2 to be played (track ordered playback)
Actual: track 8 is played for example

mp3 files with id3v2.4 tags

**Comment by karimknaebel** [comment]
Are you sure that the shuffle mode isn't enabled?

**Comment by eggsgent** [comment]
You are right, this is super embarrassing. I was just checking the context menu top right, not the icons next to the playback controls. http://i.imgur.com/60Nu3he.png
Got you a coffee :)

**Comment by karimknaebel** [comment]
Never mind, thx mate ^^

**Comment by eggsgent** [comment]
Hi again, I've been playing a bit more with shuffling and have found the following:
1. Go to Album tab an select an album
2. Press the Shuffle icon top right in the album overview

Result: playback starts, the album is shuffled
1. Open the Playback screen and press the enabled Shuffle button next to the playback buttons to disable Shuffle mode
2. Press the 3 dots context menu top right in Playback screen and select Shuffle All

Result: Media library gets shuffled, pressing Next will play next song in the library shuffle
1. Press the X top left > Go back to the album you had selected in step 1
2. Press track 1, then press Next

Result: Playback is still in Shuffle mode, but now only within the album.
This is unexpected behavior to me as I reselected an album after going out of the library shuffle list.
Is this how it should work?

**Comment by karimknaebel** [comment]
Yeah this is how it should work. Imagine like there is a global shuffle mode, which is either on or off. If you turn it on, it'll always stay on until you turn it off. If you hit shuffle all, it simply plays all songs and turns shuffle mode to on. You'll notice the same behavior in (at least almost) any other player :)

**Comment by paulheising** [comment]
I'm not really familiar with that "global shuffle" behavior. Because for my personal use, there are two general use cases how I use a music player:
- Shuffle the whole media library, like my own private radio
- Listen to an album, with no shuffle. Play the songs in the original album track order.

And maybe, sometimes I shuffle all songs from one specific interpret, but that should be it.

Would I would appreciate, whould be, if I start an album playback, shuffle mode would be turned off. Because I think this is the general intention, when listening to an album. Do it without shuffle. If you then go to the "ALL SONGS" Tab and play one, shuffle could automatically be turned on again.

This whould be the best for my personal use of phonograph. Of course. Everyone is using the app differently and so it's clear that not every feature could be provided while still keeping the app simple and tidy, which is really great about it.

Espacially the option to automatically turn shuffle mode off when starting an album playback, whould be nice and I would be very grateful for that. Maybe, if this will be implemented you could combine this with a "Play"-Button next to the album name, when viewing one album, which starts playing the album. I think this would be a bit more intuitive than having to select the first song to start album playback.

Cheers.
